[project]
name = "light-vllm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "phil", email = "171982919@qq.com"},
]
dependencies = []
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
